//! Durable migration job planning.
//!
//! Owns enqueue and inline-completion SQL for `migrate_backfill` jobs. Live
//! migration runs in the calling backend (`pg_koldstore`); there is no separate
//! leased claim worker for migrations.

use std::num::NonZeroUsize;

use koldstore_common::TableKind;
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

use koldstore_common::SqlStatement;

use crate::order::{MigrationOrdering, OrderingSource};
use crate::QualifiedTableName;

/// Managed table type recorded for migration activation.
pub use koldstore_common::TableKind as ManagedTableType;

/// Positive migration batch size.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct MigrationBatchSize(NonZeroUsize);

impl MigrationBatchSize {
    /// Creates a positive migration batch size.
    ///
    /// # Errors
    ///
    /// Returns an error when the batch size is zero.
    pub fn new(value: usize) -> Result<Self, MigrationJobError> {
        NonZeroUsize::new(value)
            .map(Self)
            .ok_or(MigrationJobError::InvalidBatchSize)
    }

    /// Returns the raw batch size.
    #[must_use]
    pub const fn get(self) -> usize {
        self.0.get()
    }
}

/// Durable migration phase names stored in `koldstore.jobs.phase`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MigrationJobPhase {
    /// Job is queued before schema-column preparation.
    Pending,
    /// Existing rows are being inserted into the clean-schema mirror.
    InitializeMirror,
    /// Migration job finished.
    Finished,
}

impl MigrationJobPhase {
    /// Returns the catalog representation.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::InitializeMirror => "initialize_mirror",
            Self::Finished => "finished",
        }
    }
}

/// JSON payload recorded on a migration backfill job.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MigrationBackfillPayload {
    /// Durable phase the migration job starts with.
    pub phase: MigrationJobPhase,
    /// Normalized target table name.
    pub table_name: String,
    /// Managed table type.
    pub table_type: TableKind,
    /// Storage binding used when the table becomes active.
    pub storage_id: Uuid,
    /// Optional user-scope column.
    pub scope_column: Option<String>,
    /// Backfill order column.
    pub order_column: String,
    /// Backfill ordering source.
    pub order_source: OrderingSource,
    /// Bounded rows per batch.
    pub batch_size: MigrationBatchSize,
    /// Optional periodic flush hot-row limit activated after migration.
    pub hot_row_limit: Option<u64>,
    /// Rows processed so far. The SQL job row is authoritative; this is for
    /// operator-readable payload snapshots.
    pub processed_rows: u64,
}

/// Migration backfill enqueue request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MigrationBackfillJobRequest {
    /// Job id generated by the caller.
    pub job_id: Uuid,
    /// Target PostgreSQL table oid.
    pub table_oid: u32,
    /// Payload stored in `koldstore.jobs.payload`.
    pub payload: MigrationBackfillPayload,
}

impl MigrationBackfillJobRequest {
    /// Creates a migration backfill request.
    #[allow(clippy::too_many_arguments)]
    #[must_use]
    pub fn new(
        job_id: Uuid,
        table_oid: u32,
        table: &QualifiedTableName,
        table_type: TableKind,
        storage_id: Uuid,
        scope_column: Option<String>,
        ordering: &MigrationOrdering,
        batch_size: MigrationBatchSize,
        hot_row_limit: Option<u64>,
    ) -> Self {
        Self {
            job_id,
            table_oid,
            payload: MigrationBackfillPayload {
                phase: MigrationJobPhase::InitializeMirror,
                table_name: normalized_table_name(table),
                table_type,
                storage_id,
                scope_column,
                order_column: ordering.column.clone(),
                order_source: ordering.source,
                batch_size,
                hot_row_limit,
                processed_rows: 0,
            },
        }
    }
}

/// Planned job enqueue statement.
#[derive(Debug, Clone, PartialEq)]
pub struct MigrationJobEnqueuePlan {
    /// Job id to bind as `$1`.
    pub job_id: Uuid,
    /// Table oid to bind as `$2`.
    pub table_oid: u32,
    /// Payload to bind as `$3`.
    pub payload: serde_json::Value,
    /// Parameterized enqueue SQL.
    pub statement: SqlStatement,
}

/// Migration job planning error.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum MigrationJobError {
    /// Table oid is missing.
    #[error("table_oid cannot be zero")]
    MissingTableOid,
    /// Batch size must be positive.
    #[error("migration batch_size must be greater than zero")]
    InvalidBatchSize,
    /// Identifier is unsafe to quote.
    #[error("invalid migration identifier `{0}`")]
    InvalidIdentifier(String),
    /// Payload serialization failed.
    #[error("migration payload serialization failed: {0}")]
    Payload(String),
    /// SPI statement metadata could not be prepared.
    #[error("{0}")]
    Spi(String),
}

/// Builds the enqueue plan for a migration backfill job.
///
/// # Errors
///
/// Returns an error when table metadata is invalid or statement metadata cannot
/// be prepared.
pub fn enqueue_migration_backfill_job_plan(
    request: MigrationBackfillJobRequest,
) -> Result<MigrationJobEnqueuePlan, MigrationJobError> {
    if request.table_oid == 0 {
        return Err(MigrationJobError::MissingTableOid);
    }

    let payload = serde_json::to_value(&request.payload)
        .map_err(|error| MigrationJobError::Payload(error.to_string()))?;
    let statement = SqlStatement::write(
        "enqueue migration backfill job",
        r#"
INSERT INTO koldstore.jobs (
    id,
    table_oid,
    scope_key,
    job_type,
    status,
    phase,
    priority,
    rows_processed,
    payload
)
VALUES (
    $1::uuid,
    $2::oid,
    '',
    'migrate_backfill',
    'pending',
    'initialize_mirror',
    100,
    0,
    $3::jsonb
)
ON CONFLICT DO NOTHING
RETURNING id
"#,
    )
    .map_err(|error| MigrationJobError::Spi(error.to_string()))?;

    Ok(MigrationJobEnqueuePlan {
        job_id: request.job_id,
        table_oid: request.table_oid,
        payload,
        statement,
    })
}

/// Plans insertion of a completed empty-table migration backfill job.
///
/// # Errors
///
/// Returns an error when SQL statement metadata cannot be prepared.
pub fn plan_completed_empty_migration_job() -> Result<SqlStatement, MigrationJobError> {
    SqlStatement::write(
        "insert completed empty migration job",
        r#"
INSERT INTO koldstore.jobs (
    id,
    table_oid,
    scope_key,
    job_type,
    status,
    phase,
    priority,
    rows_processed,
    payload,
    last_heartbeat_at,
    updated_at
)
VALUES (
    $1::uuid,
    $2::oid,
    '',
    'migrate_backfill',
    'completed',
    'finished',
    100,
    0,
    jsonb_build_object(
        'phase', 'finished',
        'table_name', $3::text,
        'table_type', $4::text,
        'storage_id', $5::uuid,
        'scope_column', $6::text,
        'processed_rows', 0
    ),
    now(),
    now()
)
"#,
    )
    .map_err(|error| MigrationJobError::Spi(error.to_string()))
}

/// Plans completion of an inline migration backfill job.
///
/// # Errors
///
/// Returns an error when SQL statement metadata cannot be prepared.
pub fn plan_complete_migration_backfill_job() -> Result<SqlStatement, MigrationJobError> {
    SqlStatement::write(
        "complete migration backfill job",
        r#"
UPDATE koldstore.jobs
SET status = 'completed',
    phase = 'finished',
    rows_processed = $3::bigint,
    batches_completed = GREATEST(batches_completed, CASE WHEN $3::bigint > 0 THEN 1 ELSE 0 END),
    payload = jsonb_set(
        jsonb_set(payload, '{phase}', '"finished"'::jsonb, true),
        '{processed_rows}',
        to_jsonb($3::bigint),
        true
    ),
    lease_owner = NULL,
    lease_expires_at = NULL,
    last_heartbeat_at = now(),
    updated_at = now()
WHERE id = $1::uuid
  AND table_oid = $2::oid
  AND job_type = 'migrate_backfill'
"#,
    )
    .map_err(|error| MigrationJobError::Spi(error.to_string()))
}

fn normalized_table_name(table: &QualifiedTableName) -> String {
    match table.schema.as_deref() {
        Some(schema) => format!("{schema}.{}", table.name),
        None => table.name.clone(),
    }
}
