//! Durable migration job planning.
//!
//! Existing-row migration is intentionally split into small catalog-visible
//! phases. A worker can crash after any committed batch; the next worker claims
//! the same job through the `koldstore.jobs` lease and skips rows that already
//! have a change-log mirror row.

use std::num::NonZeroUsize;

use koldstore_common::TableKind;
use koldstore_jobs::{LeaseEpoch, LeaseSeconds};
use serde::{Deserialize, Serialize};
use thiserror::Error;
use uuid::Uuid;

use koldstore_common::SqlStatement;

use crate::order::{MigrationOrdering, OrderingSource};
use crate::QualifiedTableName;

/// Managed table type recorded for migration activation.
pub use koldstore_common::TableKind as ManagedTableType;

/// Positive migration batch size.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(transparent)]
pub struct MigrationBatchSize(NonZeroUsize);

impl MigrationBatchSize {
    /// Creates a positive migration batch size.
    ///
    /// # Errors
    ///
    /// Returns an error when the batch size is zero.
    pub fn new(value: usize) -> Result<Self, MigrationJobError> {
        NonZeroUsize::new(value)
            .map(Self)
            .ok_or(MigrationJobError::InvalidBatchSize)
    }

    /// Returns the raw batch size.
    #[must_use]
    pub const fn get(self) -> usize {
        self.0.get()
    }
}

/// Positive migration job lease duration.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MigrationLeaseSeconds(LeaseSeconds);

impl MigrationLeaseSeconds {
    /// Creates a positive lease duration.
    ///
    /// # Errors
    ///
    /// Returns an error when the duration is zero.
    pub fn new(value: u32) -> Result<Self, MigrationJobError> {
        LeaseSeconds::new(value)
            .map(Self)
            .ok_or(MigrationJobError::InvalidLeaseSeconds)
    }

    /// Returns the raw seconds value.
    #[must_use]
    pub const fn get(self) -> u32 {
        self.0.get()
    }
}

/// Monotonic lease epoch for migration jobs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MigrationLeaseEpoch(LeaseEpoch);

impl MigrationLeaseEpoch {
    /// Creates a non-negative lease epoch.
    ///
    /// # Errors
    ///
    /// Returns an error when the epoch is negative.
    pub const fn new(value: i64) -> Result<Self, MigrationJobError> {
        match LeaseEpoch::new(value) {
            Some(value) => Ok(Self(value)),
            None => Err(MigrationJobError::InvalidLeaseEpoch),
        }
    }

    /// Returns the raw epoch value.
    #[must_use]
    pub const fn get(self) -> i64 {
        self.0.get()
    }
}

/// Migration job type.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MigrationJobKind {
    /// Initializes existing rows into the clean-schema mirror.
    Backfill,
}

impl MigrationJobKind {
    /// Returns the `koldstore.jobs.job_type` value.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Backfill => "migrate_backfill",
        }
    }
}

/// Durable migration phase names stored in `koldstore.jobs.phase`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum MigrationJobPhase {
    /// Job is queued before schema-column preparation.
    Pending,
    /// Existing rows are being inserted into the clean-schema mirror.
    InitializeMirror,
    /// Migration job finished.
    Finished,
}

impl MigrationJobPhase {
    /// Returns the catalog representation.
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Pending => "pending",
            Self::InitializeMirror => "initialize_mirror",
            Self::Finished => "finished",
        }
    }
}

/// JSON payload recorded on a migration backfill job.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MigrationBackfillPayload {
    /// Durable phase the migration job starts with.
    pub phase: MigrationJobPhase,
    /// Normalized target table name.
    pub table_name: String,
    /// Managed table type.
    pub table_type: TableKind,
    /// Storage binding used when the table becomes active.
    pub storage_id: Uuid,
    /// Optional user-scope column.
    pub scope_column: Option<String>,
    /// Backfill order column.
    pub order_column: String,
    /// Backfill ordering source.
    pub order_source: OrderingSource,
    /// Bounded rows per batch.
    pub batch_size: MigrationBatchSize,
    /// Optional periodic flush hot-row limit activated after migration.
    pub hot_row_limit: Option<u64>,
    /// Rows processed so far. The SQL job row is authoritative; this is for
    /// operator-readable payload snapshots.
    pub processed_rows: u64,
}

/// Migration backfill enqueue request.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MigrationBackfillJobRequest {
    /// Job id generated by the caller.
    pub job_id: Uuid,
    /// Target PostgreSQL table oid.
    pub table_oid: u32,
    /// Payload stored in `koldstore.jobs.payload`.
    pub payload: MigrationBackfillPayload,
}

impl MigrationBackfillJobRequest {
    /// Creates a migration backfill request.
    #[allow(clippy::too_many_arguments)]
    #[must_use]
    pub fn new(
        job_id: Uuid,
        table_oid: u32,
        table: &QualifiedTableName,
        table_type: TableKind,
        storage_id: Uuid,
        scope_column: Option<String>,
        ordering: &MigrationOrdering,
        batch_size: MigrationBatchSize,
        hot_row_limit: Option<u64>,
    ) -> Self {
        Self {
            job_id,
            table_oid,
            payload: MigrationBackfillPayload {
                phase: MigrationJobPhase::InitializeMirror,
                table_name: normalized_table_name(table),
                table_type,
                storage_id,
                scope_column,
                order_column: ordering.column.clone(),
                order_source: ordering.source,
                batch_size,
                hot_row_limit,
                processed_rows: 0,
            },
        }
    }
}

/// Planned job enqueue statement.
#[derive(Debug, Clone, PartialEq)]
pub struct MigrationJobEnqueuePlan {
    /// Job id to bind as `$1`.
    pub job_id: Uuid,
    /// Table oid to bind as `$2`.
    pub table_oid: u32,
    /// Payload to bind as `$3`.
    pub payload: serde_json::Value,
    /// Parameterized enqueue SQL.
    pub statement: SqlStatement,
}

/// Planned migration job claim statement.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MigrationJobClaimPlan {
    /// Maximum jobs to claim.
    pub limit: u32,
    /// Maximum concurrently running jobs allowed before this claim pauses.
    pub max_running_jobs: u32,
    /// Lease duration.
    pub lease_seconds: MigrationLeaseSeconds,
    /// Parameterized claim SQL.
    pub statement: SqlStatement,
}

/// Planned migration progress statement.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MigrationJobProgressPlan {
    /// Job id.
    pub job_id: Uuid,
    /// Lease owner.
    pub lease_owner: Uuid,
    /// Lease epoch.
    pub lease_epoch: MigrationLeaseEpoch,
    /// Durable phase.
    pub phase: MigrationJobPhase,
    /// Rows processed by this progress update.
    pub rows_processed_increment: u64,
    /// Parameterized progress SQL.
    pub statement: SqlStatement,
}

/// Planned mirror-initialization completion statement.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MigrationMirrorInitializationFinishPlan {
    /// Job id.
    pub job_id: Uuid,
    /// Lease owner.
    pub lease_owner: Uuid,
    /// Lease epoch.
    pub lease_epoch: MigrationLeaseEpoch,
    /// Durable phase after completion.
    pub phase: MigrationJobPhase,
    /// Parameterized completion SQL.
    pub statement: SqlStatement,
}

/// Migration job planning error.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum MigrationJobError {
    /// Table oid is missing.
    #[error("table_oid cannot be zero")]
    MissingTableOid,
    /// Batch size must be positive.
    #[error("migration batch_size must be greater than zero")]
    InvalidBatchSize,
    /// Lease seconds must be positive.
    #[error("migration lease_seconds must be greater than zero")]
    InvalidLeaseSeconds,
    /// Lease epoch must be non-negative.
    #[error("migration lease_epoch must be non-negative")]
    InvalidLeaseEpoch,
    /// Identifier is unsafe to quote.
    #[error("invalid migration identifier `{0}`")]
    InvalidIdentifier(String),
    /// Payload serialization failed.
    #[error("migration payload serialization failed: {0}")]
    Payload(String),
    /// SPI statement metadata could not be prepared.
    #[error("{0}")]
    Spi(String),
}

/// Builds the enqueue plan for a migration backfill job.
///
/// # Errors
///
/// Returns an error when table metadata is invalid or statement metadata cannot
/// be prepared.
pub fn enqueue_migration_backfill_job_plan(
    request: MigrationBackfillJobRequest,
) -> Result<MigrationJobEnqueuePlan, MigrationJobError> {
    if request.table_oid == 0 {
        return Err(MigrationJobError::MissingTableOid);
    }

    let payload = serde_json::to_value(&request.payload)
        .map_err(|error| MigrationJobError::Payload(error.to_string()))?;
    let statement = SqlStatement::write(
        "enqueue migration backfill job",
        r#"
INSERT INTO koldstore.jobs (
    id,
    table_oid,
    scope_key,
    job_type,
    status,
    phase,
    priority,
    rows_processed,
    payload
)
VALUES (
    $1::uuid,
    $2::oid,
    '',
    'migrate_backfill',
    'pending',
    'initialize_mirror',
    100,
    0,
    $3::jsonb
)
ON CONFLICT DO NOTHING
RETURNING id
"#,
    )
    .map_err(|error| MigrationJobError::Spi(error.to_string()))?;

    Ok(MigrationJobEnqueuePlan {
        job_id: request.job_id,
        table_oid: request.table_oid,
        payload,
        statement,
    })
}

/// Builds a scalable migration-job claim plan.
///
/// # Errors
///
/// Returns an error when statement metadata cannot be prepared.
pub fn claim_migration_jobs_plan(
    limit: u32,
    max_running_jobs: u32,
    lease_seconds: MigrationLeaseSeconds,
) -> Result<MigrationJobClaimPlan, MigrationJobError> {
    let statement = SqlStatement::write(
        "claim migration jobs",
        r#"
WITH running_jobs AS (
    SELECT count(*)::integer AS count
    FROM koldstore.jobs
    WHERE status = 'running'
      AND (
          lease_expires_at IS NULL
          OR lease_expires_at >= now()
      )
),
candidate AS (
    SELECT j.id
    FROM koldstore.jobs AS j
    CROSS JOIN running_jobs
    WHERE j.job_type IN ('migrate_backfill')
      AND j.status IN ('pending', 'running')
      AND running_jobs.count < $4::integer
      AND j.run_after <= now()
      AND (
          j.status = 'pending'
          OR j.lease_expires_at IS NULL
          OR j.lease_expires_at < now()
      )
      AND NOT EXISTS (
          SELECT 1
          FROM koldstore.jobs AS table_running
          WHERE table_running.table_oid = j.table_oid
            AND table_running.id <> j.id
            AND table_running.job_type IN ('flush', 'migrate_backfill')
            AND table_running.status = 'running'
            AND (
                table_running.lease_expires_at IS NULL
                OR table_running.lease_expires_at >= now()
            )
      )
    ORDER BY j.priority DESC, j.updated_at, j.id
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE koldstore.jobs AS j
SET status = 'running',
    phase = CASE WHEN j.phase = 'pending' THEN 'initialize_mirror' ELSE j.phase END,
    attempts = CASE WHEN j.status = 'pending' THEN j.attempts + 1 ELSE j.attempts END,
    lease_owner = $2::uuid,
    lease_expires_at = now() + ($3::integer * interval '1 second'),
    lease_epoch = j.lease_epoch + 1,
    updated_at = now(),
    last_heartbeat_at = now()
FROM candidate
WHERE j.id = candidate.id
RETURNING j.id, j.table_oid, j.phase, j.lease_epoch, j.checkpoint_seq, j.rows_processed, j.payload
"#,
    )
    .map_err(|error| MigrationJobError::Spi(error.to_string()))?;

    Ok(MigrationJobClaimPlan {
        limit,
        max_running_jobs,
        lease_seconds,
        statement,
    })
}

/// Builds a lease-guarded migration progress update.
///
/// # Errors
///
/// Returns an error when statement metadata cannot be prepared.
pub fn migration_job_progress_plan(
    job_id: Uuid,
    lease_owner: Uuid,
    lease_epoch: MigrationLeaseEpoch,
    phase: MigrationJobPhase,
    rows_processed_increment: u64,
) -> Result<MigrationJobProgressPlan, MigrationJobError> {
    let statement = SqlStatement::write(
        "migration job progress",
        r#"
UPDATE koldstore.jobs
SET phase = $4::text,
    rows_processed = rows_processed + $5::bigint,
    batches_completed = batches_completed + 1,
    payload = jsonb_set(payload, '{processed_rows}', to_jsonb(rows_processed + $5::bigint), true),
    last_heartbeat_at = now(),
    updated_at = now()
WHERE id = $1::uuid
  AND lease_owner = $2::uuid
  AND lease_epoch = $3::bigint
  AND status = 'running'
RETURNING id
"#,
    )
    .map_err(|error| MigrationJobError::Spi(error.to_string()))?;

    Ok(MigrationJobProgressPlan {
        job_id,
        lease_owner,
        lease_epoch,
        phase,
        rows_processed_increment,
        statement,
    })
}

/// Builds the lease-guarded clean-schema mirror initialization completion plan.
///
/// # Errors
///
/// Returns an error when statement metadata cannot be prepared.
pub fn finish_mirror_initialization_plan(
    job_id: Uuid,
    lease_owner: Uuid,
    lease_epoch: MigrationLeaseEpoch,
) -> Result<MigrationMirrorInitializationFinishPlan, MigrationJobError> {
    let statement = SqlStatement::write(
        "finish mirror initialization",
        r#"
WITH finished AS (
    UPDATE koldstore.jobs
    SET status = 'completed',
        phase = 'finished',
        lease_owner = NULL,
        lease_expires_at = NULL,
        last_heartbeat_at = now(),
        updated_at = now()
    WHERE id = $1::uuid
      AND lease_owner = $2::uuid
      AND lease_epoch = $3::bigint
      AND status = 'running'
    RETURNING table_oid
),
activated AS (
    UPDATE koldstore.schemas AS s
    SET active = true,
        initialization_state = 'complete',
        options = jsonb_set(s.options, '{migration_status}', '"active"'::jsonb, true),
        updated_at = now()
    FROM finished
    WHERE s.table_oid = finished.table_oid
    RETURNING s.table_oid
)
SELECT count(*) FROM activated
"#,
    )
    .map_err(|error| MigrationJobError::Spi(error.to_string()))?;

    Ok(MigrationMirrorInitializationFinishPlan {
        job_id,
        lease_owner,
        lease_epoch,
        phase: MigrationJobPhase::Finished,
        statement,
    })
}

fn normalized_table_name(table: &QualifiedTableName) -> String {
    match table.schema.as_deref() {
        Some(schema) => format!("{schema}.{}", table.name),
        None => table.name.clone(),
    }
}
